apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pubsub
  labels:
    app: pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub
  template:
    metadata:
      labels:
        app: pubsub
    spec:
      containers:
      - name: pubsub
        image: jicowan/pubsub
        env:
          - name: "REDIS_URL"
            value: {{ .Release.Name }}-redis-master.default.svc.cluster.local
          - name: "GAME_SERVER_GROUP_NAME"
            value: {{ .Values.gameliftDaemon.gameServerGroupName }}
          - name: "AWS_REGION"
            value: {{ .Values.aws.region }}
        imagePullPolicy: Always
