# Default values for gamelift-daemonset.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

aws: 
  region: us-west-2
  
redis: 
  tls:
    authClients: false
  usePassword: false