apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsubv2
  labels:
    app: pubsubv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsubv2
  template:
    metadata:
      labels:
        app: pubsubv2
    spec:
      containers:
      - name: pubsubv2
        image: jicowan/pubsubv2
        env:
          - name: "REDIS_URL"
            value: "gameliftcache.hmhiju.ng.0001.usw2.cache.amazonaws.com:6379"
          - name: "AWS_REGION"
            value: "us-west-2"
        volumeMounts:
          - name: config
            mountPath: /etc/fleetiq/
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: fleetiqconfig.yaml
      serviceAccount: fleetiq
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleetiq
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["fleetiqconfig.yaml"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-reader
  namespace: default
subjects:
- kind: ServiceAccount
  name: fleetiq
  namespace: default
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io